// Generated by gencpp from file test/person.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_PERSON_H
#define TEST_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : name()
    , age(0)
    , hight(0.0)  {
    }
  person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , hight(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _hight_type;
  _hight_type hight;





  typedef boost::shared_ptr< ::test::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::person_<ContainerAllocator> const> ConstPtr;

}; // struct person_

typedef ::test::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::test::person > personPtr;
typedef boost::shared_ptr< ::test::person const> personConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::person_<ContainerAllocator1> & lhs, const ::test::person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.hight == rhs.hight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::person_<ContainerAllocator1> & lhs, const ::test::person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56af71e4d5123f01ffc8a50934f9ea28";
  }

  static const char* value(const ::test::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56af71e4d5123f01ULL;
  static const uint64_t static_value2 = 0xffc8a50934f9ea28ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/person";
  }

  static const char* value(const ::test::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
"float32 hight\n"
;
  }

  static const char* value(const ::test::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.hight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "hight: ";
    Printer<float>::stream(s, indent + "  ", v.hight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_PERSON_H
